spring:
  application:
    name:  mymall
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8   #最大可连接
        max-idle: 8     #最大空闲连接
        max-wait: -1ms  #拥塞等待时间
        min-idle: 0     #最小可连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath*:com/**/mapper/*.xml

redis:
  key:
    prefix:
      authCode: my_mall_
    expire:
      authCode: 120
